version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:8080"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf

    php:
        image: php:7-fpm
        volumes:
            - ./code:/code
