version: "2"

services:
    web:
        build: ./docker/nginx
        ports:
            - "80:8080"
        volumes:
            - ./code:/code

    php:
        build: ./docker/php/
        volumes:
            - ./code:/code

    composer:
        build: ./docker/composer
        volumes:
            - ./code:/app
        command: install
