version: "2"

services:
    web:
        image: nginx:1.13.1-alpine
        depends_on:
            - php
        ports:
            - "81:8080"
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
            - ./code:/app

    php:
        build: ./code
        volumes:
            - ./code:/app

    composer:
        image: composer:1.5.2
        volumes:
            - ./code:/app
        command: install

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - /mysql/data:/var/lib/mysql
