version: "2"

services:
    web:
        image: nginx:1.13.1-alpine
        ports:
            - "80:8080"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf

    php:
        build: ./docker/php/
        volumes:
            - ./code:/code
