version: "2"

services:
    web:
        build: ./docker/nginx
        depends_on:
            - php
        ports:
            - "80:8080"
        volumes:
            - ./code:/code

    php:
        image: php:7.1.8-fpm-alpine
        depends_on:
            - composer
        volumes:
            - ./code:/code

    composer:
        image: composer:1.5.2
        volumes:
            - ./code:/app
        command: install
