version: "2"

services:
    web:
        build: ./docker/nginx
        ports:
            - "80:8080"
        volumes:
            - ./code:/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf

    php:
        build: ./docker/php/
        volumes:
            - ./code:/code
