version: "3"

services:
    web:
        image: nginx:1.13.1-alpine
        depends_on:
            - php
        ports:
            - "80:8080"
        volumes:
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
            - ./code:/app

    php:
        image: php:7.1.8-fpm-alpine
        volumes:
            - ./code:/app

    composer:
        image: composer:1.5.2
        volumes:
            - ./code:/app
        command: install
        deploy:
            restart_policy:
                condition: none

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - /mysql/data:/var/lib/mysql
